version: 2
updates:
  # Maintain dependencies for backend
  - package-ecosystem: "gradle"
    directory: "backend/"
    target-branch: "main"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore:"
    groups:
      main:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
        patterns:
          - "*"

  # Maintain dependencies for frontend
  - package-ecosystem: "npm"
    directory: "frontend/"
    target-branch: "main"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore:"
    groups:
      main:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
        patterns:
          - "*"
